/* Generated By:JJTree: Do not edit this line. ClassDecl.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lexer;

public
class ClassDecl extends SimpleNode {
  public ClassDecl(int id) {
    super(id);
  }

  public ClassDecl(Lexer p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5f851a8dba450a40ed629e49ff366b0a (do not edit this line) */
