/* Generated By:JJTree: Do not edit this line. E1.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lexer;

public
class E1 extends SimpleNode {
  public E1(int id) {
    super(id);
  }

  public E1(Lexer p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8af27ac5c207015fa16589f12c3159c2 (do not edit this line) */
