/* Generated By:JJTree: Do not edit this line. E5Cont.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lexer;

public
class E5Cont extends SimpleNode {
  public E5Cont(int id) {
    super(id);
  }

  public E5Cont(Lexer p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=acc357d90a96f725c75d3a51ca7c9e08 (do not edit this line) */
