/* Generated By:JJTree: Do not edit this line. E6.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lexer;

public
class E6 extends SimpleNode {
  public E6(int id) {
    super(id);
  }

  public E6(Lexer p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cb9dee38df0ff25dbbac3248ee58240c (do not edit this line) */
