/* Generated By:JJTree: Do not edit this line. ExpList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lexer;

public
class ExpList extends SimpleNode {
  public ExpList(int id) {
    super(id);
  }

  public ExpList(Lexer p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7d2a1472f491ce2982314262d7fc5884 (do not edit this line) */
