/* Generated By:JJTree: Do not edit this line. FormalRest.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lexer;

public
class FormalRest extends SimpleNode {

	private String name;

	public FormalRest(int id) {
		super(id);
	}

	public FormalRest(Lexer p, int id) {
		super(p, id);
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	public String toString() {
		return super.toString() + "(" + name + ")";
	}

}
/* JavaCC - OriginalChecksum=bb6dc3af303fcd8f101b0721e1c70214 (do not edit this line) */
