/* Generated By:JJTree: Do not edit this line. FormalList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lexer;

public
class FormalList extends SimpleNode {
  public FormalList(int id) {
    super(id);
  }

  public FormalList(Lexer p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0ba785bca515b000fc1eb5b5614a39f5 (do not edit this line) */
