/* Generated By:JavaCC: Do not edit this line. LexerTreeConstants.java Version 5.0 */
package lexer;

public interface LexerTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTTESTNODE = 1;
  public int JJTCLASSDECL = 2;
  public int JJTVARDECL = 3;
  public int JJTMETHODDECL = 4;
  public int JJTFORMALLIST = 5;
  public int JJTFORMALREST = 6;
  public int JJTTYPE = 7;
  public int JJTSTMT = 8;
  public int JJTEXP = 9;
  public int JJTE1 = 10;
  public int JJTE1CONT = 11;
  public int JJTE2 = 12;
  public int JJTE2CONT = 13;
  public int JJTE3 = 14;
  public int JJTE3CONT = 15;
  public int JJTE4 = 16;
  public int JJTE4CONT = 17;
  public int JJTE5 = 18;
  public int JJTE5CONT = 19;
  public int JJTE6 = 20;
  public int JJTEXPLIST = 21;
  public int JJTEXPREST = 22;


  public String[] jjtNodeName = {
    "Program",
    "TestNode",
    "ClassDecl",
    "VarDecl",
    "MethodDecl",
    "FormalList",
    "FormalRest",
    "Type",
    "Stmt",
    "Exp",
    "E1",
    "E1Cont",
    "E2",
    "E2Cont",
    "E3",
    "E3Cont",
    "E4",
    "E4Cont",
    "E5",
    "E5Cont",
    "E6",
    "ExpList",
    "ExpRest",
  };
}
/* JavaCC - OriginalChecksum=9b9608b0d86594136064a76f73f5c819 (do not edit this line) */
