/* Generated By:JJTree: Do not edit this line. MainClass.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lexer;

public
class MainClass extends SimpleNode {
  public MainClass(int id) {
    super(id);
  }

  public MainClass(Lexer p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b645a637ba8993531736d30518182fb8 (do not edit this line) */
