/* Generated By:JJTree: Do not edit this line. MethodDecl.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lexer;

public
class MethodDecl extends SimpleNode {
  public MethodDecl(int id) {
    super(id);
  }

  public MethodDecl(Lexer p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ba955e37a17bc86108731136437bad33 (do not edit this line) */
