/* Generated By:JJTree: Do not edit this line. Stmt.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lexer;

public
class Stmt extends SimpleNode {
  public Stmt(int id) {
    super(id);
  }

  public Stmt(Lexer p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=79188639f98ec5c0a1da9aaed81dc2d7 (do not edit this line) */
