/* Generated By:JJTree: Do not edit this line. Type.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lexer;

public
class Type extends SimpleNode {
	
	private String name;
	
  public Type(int id) {
    super(id);
  }

  public Type(Lexer p, int id) {
    super(p, id);
  }

public String getName() {
	return name;
}

public void setName(String name) {
	this.name = name;
}

}
/* JavaCC - OriginalChecksum=ae84556a2cae509241b4c4f412ad0bb7 (do not edit this line) */
