/* Generated By:JJTree: Do not edit this line. E0.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package mjc.lexer;

import mjc.type_checker.SymTable;

public
class E0 extends SimpleNode {
	public E0(int id) {
		super(id);
	}

	public E0(Lexer p, int id) {
		super(p, id);
	}
	
	public Type pass2(SymTable symTable) {
		Type type = ((E1)children[0]).pass2(symTable);
		return ((E0Cont)children[1]).pass2(symTable, type);
	}

}
/* JavaCC - OriginalChecksum=7a1d6d0537eff532b56a1f8c0fd9ce84 (do not edit this line) */
