/* Generated By:JJTree: Do not edit this line. E0Cont.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package mjc.lexer;

import generator.JasminPrinter;
import mjc.errors.TypeError;
import mjc.type_checker.SymTable;

public class E0Cont extends SimpleNode {
	public E0Cont(int id) {
		super(id);
	}

	public E0Cont(Lexer p, int id) {
		super(p, id);
	}

	public Type pass2(SymTable symTable, Type type) {
		if (children != null) {
			int label = JasminPrinter.incrementLabel();
			JasminPrinter.print_ifne(label);
			Type type2 = ((E1)children[0]).pass2(symTable);
			if (!type.isBoolean() || !type2.isBoolean()) {
				throw new TypeError("Invalid types for || operation: " + type.toShortString() + " and " + type2.toShortString());
			}
			int nextLabel = JasminPrinter.incrementLabel();
			JasminPrinter.print_ifne(label);
			JasminPrinter.print_ldc(0);
			JasminPrinter.print_goto(nextLabel);
			JasminPrinter.print_label(label);
			JasminPrinter.print_ldc(1);
			JasminPrinter.print_label(nextLabel);
			JasminPrinter.print_nop();
			return ((E0Cont)children[1]).pass2(symTable, type2);
		} else {
			return type;
		}
	}

}
/* JavaCC - OriginalChecksum=15f872ec2ea78ce07c4ef77dd1e60829 (do not edit this line) */
