/* Generated By:JJTree: Do not edit this line. E1Cont.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package mjc.lexer;

public
class E1Cont extends SimpleNode {
	public E1Cont(int id) {
		super(id);
	}

	public E1Cont(Lexer p, int id) {
		super(p, id);
	}
	
	public String toString() {
		return super.toString() + " " + (children != null ? "&&" : "");
	}

}
/* JavaCC - OriginalChecksum=e84b958be354bfb485fce45fbc27b9b9 (do not edit this line) */
