/* Generated By:JJTree: Do not edit this line. E2.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package mjc.lexer;

public
class E2 extends SimpleNode {
  public E2(int id) {
    super(id);
  }

  public E2(Lexer p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2ed3a52bc67a82003d4cc02f9fd260fa (do not edit this line) */
