/* Generated By:JJTree: Do not edit this line. E2Cont.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package mjc.lexer;

public
class E2Cont extends SimpleNode {
	public E2Cont(int id) {
		super(id);
	}

	public E2Cont(Lexer p, int id) {
		super(p, id);
	}
	
	public String toString() {
		return super.toString() + " " + (children != null ? "<" : "");
	}

}
/* JavaCC - OriginalChecksum=c8ec47beb7ccd3714dc107074d649c62 (do not edit this line) */
