/* Generated By:JJTree: Do not edit this line. E4.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package mjc.lexer;

public
class E4 extends SimpleNode {
  public E4(int id) {
    super(id);
  }

  public E4(Lexer p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f2dffbc9211a500b42586ce8b0942450 (do not edit this line) */
