/* Generated By:JJTree: Do not edit this line. E4Cont.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package mjc.lexer;

public
class E4Cont extends SimpleNode {
	public E4Cont(int id) {
		super(id);
	}

	public E4Cont(Lexer p, int id) {
		super(p, id);
	}
	
	public String toString() {
		return super.toString() + " " + (children != null ? "*" : "");
	}

}
/* JavaCC - OriginalChecksum=41dedf48319ad2999413bc8be5a75888 (do not edit this line) */
