/* Generated By:JJTree: Do not edit this line. E4Cont.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package mjc.lexer;

import generator.JasminPrinter;
import mjc.errors.TypeError;
import mjc.type_checker.SymTable;

public class E4Cont extends SimpleNode {
	public E4Cont(int id) {
		super(id);
	}

	public E4Cont(Lexer p, int id) {
		super(p, id);
	}
	
	public Type pass2(SymTable symTable, Type type) {
		if (children != null) {
			Type type2 = ((E5)children[0]).pass2(symTable);
			if (!type.isInt() || !type2.isInt()) {
				throw new TypeError("Invalid types for multiplication: " + type.toShortString() + " and " + type2.toShortString());
			}
			JasminPrinter.print_imul();
			return ((E4Cont)children[1]).pass2(symTable, type2);
		}
		return type;
	}
	
	public String toString() {
		return super.toString() + " " + (children != null ? "*" : "");
	}

}
/* JavaCC - OriginalChecksum=41dedf48319ad2999413bc8be5a75888 (do not edit this line) */
