/* Generated By:JJTree: Do not edit this line. E5.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package mjc.lexer;

public
class E5 extends SimpleNode {
	
	private E5Type type;
	
	public E5(int id) {
		super(id);
	}

	public E5(Lexer p, int id) {
		super(p, id);
	}
	
	public void setType(E5Type type) {
		this.type = type;
	}
	
	public E5Type getType() {
		return type;
	}
	
	public enum E5Type {
		NOT;
	}
	
	public String toString() {
		return super.toString() + " " + (type != null ? "!" : "");
	}

}
/* JavaCC - OriginalChecksum=eccc4f05fcbf876597c4cee6ddd13727 (do not edit this line) */
