/* Generated By:JJTree: Do not edit this line. E6.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package mjc.lexer;

import generator.JasminPrinter;
import mjc.errors.DummyException;
import mjc.errors.TypeError;
import mjc.type_checker.SymTable;

public
class E6 extends SimpleNode {
	
	private String image;
	private E6Type type;
	
	public E6(int id) {
		super(id);
	}

	public E6(Lexer p, int id) {
		super(p, id);
	}
	
	public enum E6Type {
		ID, INT_LIT, TRUE, FALSE, PAREN, THIS, NEW_INT_ARRAY, NEW_ID;
	}
	
	public void setType(E6Type type) {
		this.type = type;
	}
	
	public E6Type getType() {
		return type;
	}
	
	public void setImage(String image) {
		this.image = image;
	}
	
	public String getImage() {
		return image;
	}
	
	public Type pass2(SymTable symTable) {
		if (type == E6Type.ID) {
			VarDecl varDecl = symTable.getVariableNode(image);
			if (varDecl.getType().isCustom()) {
				JasminPrinter.print_aload(symTable.getVariableIndex(varDecl.getName()));
			} else {
				JasminPrinter.print_iload(symTable.getVariableIndex(varDecl.getName()));
			}
			return varDecl.getType();
		} else if (type == E6Type.INT_LIT) {
			int val;
			try {
				val = Integer.parseInt(image);
			} catch (NumberFormatException e) {
				throw new DummyException("Invalid value for integer literal: " + image);
			}
			JasminPrinter.print_ldc(val);
			return Type.createIntType();
		} else if (type == E6Type.TRUE) {
			JasminPrinter.print_ldc(1);
			return Type.createBooleanType();
		} else if (type == E6Type.FALSE) {
			JasminPrinter.print_ldc(0);
			return Type.createBooleanType();
		} else if (type == E6Type.PAREN) {
			return ((Exp)children[0]).pass2(symTable);
		} else if (type == E6Type.THIS) {
			return Type.createCustomType(symTable.getCurrentClass().getName());
		} else if (type == E6Type.NEW_INT_ARRAY) {
			Type arraySize = ((Exp)children[0]).pass2(symTable);
			if (!arraySize.isInt()) {
				throw new TypeError("Non-int argument for array initialization");
			}
			return Type.createIntArrayType();
		} else if (type == E6Type.NEW_ID) {
			ClassDecl classDecl = symTable.getClassNode(image);
			return Type.createCustomType(classDecl.getName());
		} else {
			throw new DummyException("Unknown E6Type");
		}
	}
	
	public String toString() {
		return super.toString() + " " + type + (image != null ? "(" + image + ")" : "");
	}

}
/* JavaCC - OriginalChecksum=cb9dee38df0ff25dbbac3248ee58240c (do not edit this line) */
