/* Generated By:JJTree: Do not edit this line. ExpRest.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package mjc.lexer;

public
class ExpRest extends SimpleNode {
  public ExpRest(int id) {
    super(id);
  }

  public ExpRest(Lexer p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b9eee3b5993976e8b9c8b940de4393ed (do not edit this line) */
