/* Generated By:JJTree: Do not edit this line. FormalRest.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package mjc.lexer;

import mjc.type_checker.SymTable;

public class FormalRest extends SimpleNode {

	private String name;

	public FormalRest(int id) {
		super(id);
	}

	public FormalRest(Lexer p, int id) {
		super(p, id);
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	public void pass2(SymTable symTable) {
		Type type = (Type)children[0];
		type.pass2(symTable);
		VarDecl varDecl = VarDecl.createVarDecl(type, name);
		symTable.addVariableNode(varDecl);
	}
	
	public String getTypeDescriptor() {
		return ((Type)children[0]).getTypeDescriptor();
	}
	
	public String toString() {
		return super.toString() + "(" + name + ")";
	}

}
/* JavaCC - OriginalChecksum=bb6dc3af303fcd8f101b0721e1c70214 (do not edit this line) */
