/* Generated By:JJTree: Do not edit this line. MainClass.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package mjc.lexer;

public
class MainClass extends SimpleNode {
	
	private String name;
	
  public MainClass(int id) {
    super(id);
  }

  public MainClass(Lexer p, int id) {
    super(p, id);
  }
  
  public void setName(String name) {
	  this.name = name;
  }
  
  public String getname() {
	  return name;
  }
  
  public String toString() {
	  return super.toString() + "(" +  name + ")";
  }

}
/* JavaCC - OriginalChecksum=b645a637ba8993531736d30518182fb8 (do not edit this line) */
