/* Generated By:JJTree: Do not edit this line. MethodDecl.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package mjc.lexer;

public
class MethodDecl extends SimpleNode {

	private String name;

	public MethodDecl(int id) {
		super(id);
	}

	public MethodDecl(Lexer p, int id) {
		super(p, id);
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	public String getCanonicalString() {
		StringBuilder sb = new StringBuilder(name);
		sb.append('(');
		((FormalList)children[1]).appendCanonicalName(sb);
		sb.append(')');
		return sb.toString();
	}
	
	public static String getCanonicalString(String name, ExpList expList) {
		return null; // TODO
	}
	
	public String toString() {
		return super.toString() + "(" + name + ")";
	}

}
/* JavaCC - OriginalChecksum=ba955e37a17bc86108731136437bad33 (do not edit this line) */
